### ISSUE TITLE
Timed token handling

### ISSUE THREAD

**Issue by sbor23** [adfinis-sygroup/customer-center#117]
Timed has changed they way tokens are handled, due to necessary backend changes.
See this frontend PR for what's necessary to adapt: https://github.com/adfinis-sygroup/timed-frontend/pull/388

**Comment by sbor23** [comment]
Also this PR for session store changes: https://github.com/adfinis-sygroup/timed-frontend/pull/389

**Comment by velrest** [comment]
This was resolved with #122 .

**Comment by sbor23** [comment]
We can actually reuse this issue because it will change again in a moment, moving to OIDC

**Comment by velrest** [comment]
@sbor23 Fair point. Is there already a deadline or a timerange for the timed oidc change?

**Comment by sbor23** [comment]
Not yet as I'm informed. I should take at least two more weeks.
For reference, this is the backend PR https://github.com/adfinis-sygroup/timed-backend/pull/560
